modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/bl4ckscor3/CookieBlock/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cookie-block"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="cookieblock" #mandatory
version="v1.2" #mandatory
displayName="Cookie Block" #mandatory
description='''A cookie block.''' #mandatory

[[dependencies.cookieblock]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookieblock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"